version: '3.8'

services:

  db:
    image: mariadb:10.11
    container_name: centroplus-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: centroplus
      MYSQL_USER: centroplus_user
      MYSQL_PASSWORD: centroplus_pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build: ./backend-api
    container_name: centroplus-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: centroplus
      DB_USER: centroplus_user
      DB_PASS: centroplus_pass
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: centroplus-web
    ports:
      - "80:80"
    volumes:
      - ./web-html:/usr/share/nginx/html:ro
    depends_on:
      - api

volumes:
  db-data:
